openapi: 3.0.3
info:
  title: LogOut JSON Server
  description: this is Logout server
  contact:
    name: API Support
    email: trmtikko@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1
servers:
  - url: https://logout-theta.vercel.app/api/
    description: /auth/* のエンドポイントには api_key が必要
paths:
  /auth/mintNFT:
    $ref: './paths/auth/mintNFT/index.yaml'
  /auth/mintToken:
    $ref: './paths/auth/mintToken/index.yaml'
  /auth/deleteTodayLog:
    $ref: './paths/auth/deleteTodayLog/index.yaml'
  /utils/getNftDatas/${NFTid}:
    $ref: './paths/utils/getNftData/index.yaml'
  /utils/getWeeklySleeps/${address}:
    $ref: './paths/utils/getWeeklySleeps/index.yaml'
  /utils/getUserNfts/${address}:
    $ref: './paths/utils/getUserNfts/index.yaml'
